### ISSUE TITLE
Error while handling API request, no other debugging info

### ISSUE THREAD

**Issue by earwig** [valhallasw/plagiabot#14]
URL: https://tools.wmflabs.org/eranbot/plagiabot/api.py?action=suspected_diffs&page_title=User:EarwigBot/Copyvios/Tests/2&lang=en&report=1

Output:

```
Error encountered while handling the request. Please report a bug: https://github.com/valhallasw/plagiabot/issues
[]
```

**Comment by eranroz** [comment]
Caused by: https://phabricator.wikimedia.org/T179227 (it used different configuration file)
Fixed on production
