### ISSUE TITLE
suspected_diffs API returning error

### ISSUE THREAD

**Issue by ragesoss** [valhallasw/plagiabot#18]
It looks like the suspected_diffs API has been broken for around the last month: https://tools.wmflabs.org/eranbot/plagiabot/api.py?action=suspected_diffs

February 27 is the last time dashboard.wikiedu.org registered any new suspected diffs from student editors, so I'm guessing it's been throwing that error since soon after that date.

**Comment by ragesoss** [comment]
@eranroz @MusikAnimal any ideas about this? I've tried to get to the root error to troubleshoot it, but I'm stuck with errors trying to install `oursql` on Toolforge.

**Comment by MusikAnimal** [comment]
I'm not sure :( I have made only minor contributions to this repo. If it stopped working around a month ago, that might be because something broke after the migration to Debian Stretch.

**Comment by eranroz** [comment]
Sorry Sage for the delayed response... anyway I just fixed it there in the server - this is due to deprecation of oursql and migration to new server. I'll update the repo with pymysql as alternative

**Comment by ragesoss** [comment]
Thank you!
