### ISSUE TITLE
API does not handle errors

### ISSUE THREAD

**Issue by fhocutt** [valhallasw/plagiabot#6]
The API should handle common errors with an error code/message or at least a blank result, rather than serving error pages with a HTML stack trace, like this one: http://tools.wmflabs.org/eranbot/plagiabot/api.py?action=suspected_diffs&page_title=%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B9%20%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87&report=1

**Comment by eranroz** [comment]
Fixed in 2cbc104.

**Comment by kaldari** [comment]
Looks good to me. This can probably be closed now.
